### ISSUE TITLE
Create sliding window function

### ISSUE THREAD

**Issue by Abhishaike** [Abhishaike/ASL_Translation#1]
Function must create dynamic (as in, changeable) and SQUARE windows, given an image. You will not know the image size beforehand, so account for that in your function. Ideally, try to use a generator for this.

**Comment by Abhishaike** [comment]
@loganpadon and @AneeshSaripalli, try to work together on this and meet outside of build nights

**Comment by loganpadon** [comment]
We need to decide on a stride and size of the square.
