### ISSUE TITLE
Investigate color segmentation and write a draft function for it

### ISSUE THREAD

**Issue by Abhishaike** [Abhishaike/ASL_Translation#2]
Look into K-Means, or other clustering algos, to find good color ranges to segment out a hand.

**Comment by Abhishaike** [comment]
@evanwsun and @briannoogin, try to work together on this and meet up outside of build nights to work on this

**Comment by briannoogin** [comment]
we're done with color segmentation. We are currently trying to figure out how to insert a boundary box for the hand.

**Comment by briannoogin** [comment]
I'm working on a live-stream implementation for the bounding box.
