### ISSUE TITLE
Classifer creation (no coding, just 🤔🤔🤔)

### ISSUE THREAD

**Issue by Abhishaike** [Abhishaike/ASL_Translation#3]
Investigate what type of classifier we want to end up using. Right now, I'm thinking SVM, but there may be faster options out there. This investigation should be done for both hand/not-hand (binary) and ASL translation (multi class). Remember, we're using HoG features.

**Comment by loganpadon** [comment]
Need two classifiers, one for hand/not hand, one for the letters of the alphabet. SVM suggested for Hand/Not, random forests for letters.

**Comment by loganpadon** [comment]
Try next: use a smaller image, or downsize the HOG somehow.

**Comment by alexbaselice** [comment]
https://stackoverflow.com/questions/28390614/opencv-hogdescripter-python

This shows how to get the hog of a smaller block.

**Comment by alexbaselice** [comment]
Added an example of a two class SVC with webcam feedback on branch "alex". The SVC is trained with HOG computed from two images.

**Comment by loganpadon** [comment]
Zip and put dataset in slack. Mess with numbers to try and get a higher score.

**Comment by loganpadon** [comment]
**http://scikit-learn.org/stable/modules/model_persistence.html**

Use this to try and save the model so we don't have to train it on load every time.

**Comment by alexbaselice** [comment]
I've pushed my updated hog example file to branch Alex. 
Here's the data I was using
[6ClassData.zip](https://github.com/Abhishaike/ASL_Translation/files/1746647/6ClassData.zip).

Things to try: crop our training data and our real-time image using the team's way of detecting the hand bounding box.
